// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fslqlkqjechlvvziaydj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbHFsa3FqZWNobHZ2emlheWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzQxMTcsImV4cCI6MjA3MTcxMDExN30.sUH8IxKD3sA885fJby86_7a8ZJZ_AKoSn-KBGjzACn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});